default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  user: cafeteriaadmin
  password: cafeteriaPassword
  database: cafeteria_management

# test:
#   <<: *default
#   database: cafeteria_management_test

# production:
#   <<: *default
#   database: cafeteria_management_production
#   username: cafeteria_management
#   password: <%= ENV['CAFETERIA_MANAGEMENT_DATABASE_PASSWORD'] %>
