default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: cafeteria_management
  user: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  # user: postgres
  # password: changeme
# test:
#   <<: *default
#   database: cafeteria_management_test

# production:
#   <<: *default
#   database: cafeteria_management_production
#   username: cafeteria_management
#   password: <%= ENV['CAFETERIA_MANAGEMENT_DATABASE_PASSWORD'] %>
