owner = Role.create(name: "Owner")
Role.create(name: "Billing Clerk")
customer = Role.create!(name: "Online Customer")

User.create(role_id: owner.id, name: "Admin", email: "owner@email.com", password: "owner")
User.create(role_id: customer.id, name: "Customer", email: "customer@email", password: "customer")

brakefast = MenuCategory.create(name: "Breakfast")
lunch = MenuCategory.create(name: "Lunch")
dinner = MenuCategory.create(name: "Dinner")

MenuItem.create(menu_category_id: brakefast.id, name: "Idly", price: 10)
MenuItem.create(menu_category_id: brakefast.id, name: "Pongal", price: 50)
MenuItem.create(menu_category_id: brakefast.id, name: "Poori", price: 30)
MenuItem.create(menu_category_id: brakefast.id, name: "Idiyappam", price: 30)
MenuItem.create(menu_category_id: brakefast.id, name: "Appam", price: 30)

MenuItem.create(menu_category_id: lunch.id, name: "Meals", price: 80)
MenuItem.create(menu_category_id: lunch.id, name: "Sambar Raice", price: 50)
MenuItem.create(menu_category_id: lunch.id, name: "Tomato Raice", price: 50)
MenuItem.create(menu_category_id: lunch.id, name: "Pulao", price: 60)
MenuItem.create(menu_category_id: lunch.id, name: "Veg Biriyani", price: 60)
MenuItem.create(menu_category_id: dinner.id, name: "Chicken Biriyani", price: 100, veg: false)
MenuItem.create(menu_category_id: dinner.id, name: "Mutton Biriyani", price: 200, veg: false)

MenuItem.create(menu_category_id: dinner.id, name: "Parotta", price: 10)
MenuItem.create(menu_category_id: dinner.id, name: "Chapati", price: 10)
MenuItem.create(menu_category_id: dinner.id, name: "Veg Fried Rice", price: 100)
MenuItem.create(menu_category_id: dinner.id, name: "Chicken Fried Rice", price: 120, veg: false)
MenuItem.create(menu_category_id: dinner.id, name: "Chicken Noodles", price: 120, veg: false)
